version: '3.2'
services:
    prometheus:
        image: prom/prometheus:latest
        volumes:
            - ./prometheus/alert.rules:/etc/prometheus/alert.rules
            - ./prometheus:/etc/prometheus/
        command:
            - --config.file=/etc/prometheus/prometheus.yml
        ports:
            - '9090:9090'
        restart: always
        networks:
          prometheus:
            aliases:
              - prometheus

    node-exporter:
        image: prom/node-exporter
        hostname: node-exporter
        volumes:
            - /proc:/host/proc:ro
            - /sys:/host/sys:ro
            - /:/rootfs:ro
        command:
            - --path.procfs=/host/proc
            - --path.sysfs=/host/sys
            - --collector.filesystem.ignored-mount-points
            - ^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)
        ports:
            - '9100:9100'
        restart: always
        networks:
          prometheus:
            aliases:
              - exporter

    grafana:
        image: grafana/grafana
        hostname: grafana
        depends_on:
           - prometheus
        ports:
           - '3000:3000'
        volumes:
           - ./grafana:/var/lib/grafana
           - ./grafana/provisioning/:/etc/grafana/provisioning/
        restart: always
        user: "104"
        networks:
          prometheus:
            aliases:
              - grafana

    black-exporter:
        image: prom/blackbox-exporter
        hostname: black-exporter
        volumes:
           - ./blackbox.yml:/config/blackbox.yml
        command:
           - '--config.file=./config/blackbox.yml'
        ports:
           - '9115:9115'
        restart: always
        networks:
          prometheus:
            aliases:
              - blackbox

    alertmanager:
        image: prom/alertmanager:v0.21.0
        ports:
          - '9093:9093'
        volumes:
          - ./alertmanager/:/etc/alertmanager/
        restart: always
        command:
          - '--config.file=/etc/alertmanager/config.yml'
          - '--storage.path=/etc/alertmanager/data'
        user: "105"
        networks:
          prometheus:
            aliases:
              - alertmanager

    alertmanager-bot:
        command:
           - --alertmanager.url=http://alertmanager:9093
           - --log.level=info
           - --store=bolt
           - --bolt.path=/data/bot.db
        environment:
          TELEGRAM_ADMIN: "608168305"
          TELEGRAM_TOKEN: 883582630:AAEh3WxFGZAgsrOAuk9p1dlhMO8LpGfVwVA
        image: metalmatze/alertmanager-bot:0.4.3
        ports:
           - '8080:8080'
        restart: always
        volumes:
           - ./data:/data
        networks:
          prometheus:
            aliases:
              - alertmanager-bot

networks:
  prometheus:
    driver: bridge